general:
  cpiApiServiceKeyCredentialsId: "desgauthapikey"
  integrationFlowId: "calling_iflows_from_other_cpi_account_Created"

stages:
  Upload:
    enabled: true
  Deploy:
    enabled: false
  Integration Test:
    enabled: false

steps:
  integrationArtifactUpload:
    integrationFlowName: "calling_iflows_from_other_cpi_account_Created"
