# General settings for the pipeline
general:
  collectTelemetryData: false

stages:
  # The init stage connects to CPI using your service key
  init:
    integrationSuite:
      # This ID must match the credential you created in Step 2
      apiServiceKey: 'cpi-service-key'

  # The deploy stage pushes the iFlow and applies the configuration
  deploy:
    integrationSuite:
      deploySteps:
        - deployStrategy: 'IntegrationFlow'
          # The name of your iFlow .zip file in GitHub
          filePath: 'calling_iflows_from_other_cpi_account.zip'
          # The name of your JSON config file in GitHub
          configurationFilePath: 'prod_config.json'
